import { createContext, useContext, useEffect, useState } from "react";

const copy = {
  en: {
    home:"Home", crops:"Crops", disease:"Disease Check", planner:"Planner", switchToHindi:"हिंदी",
    cropRecommendation:"Crop Recommendation", diseaseDetector:"Disease Detector", cropPlanner:"Crop Planner",
    farmTools:"FARM TOOLS", helpToday:"How can we help today?", hero:"Better decisions for every season.",
    heroText:"Simple crop guidance, disease checks and crop planning made for your farm.",
    heroLabel:"SMART FARMING, SIMPLIFIED", heroBadge:"🌾 KisanFinTech", heroPhotoTag:"Built for everyday farmers", heroReferenceTitle:"Better decisions for a prosperous harvest.", heroReferenceText:"AI-powered insights, real-time data and personalized guidance for every farmer.", healthySoil:"HEALTHY SOIL", healthyCrops:"HEALTHY CROPS", sustainableFuture:"SUSTAINABLE FUTURE", greenerTomorrow:"Together for a greener tomorrow.", recommendedFertilizers:"Recommended Fertilizers", fertilizerNamesOnly:"Suggested fertilizer names for this crop.", fertilizerBasedOnModel:"Predicted by the fertilizer model using your farm conditions.", recommendedFertilizer:"Recommended fertilizer", fertilizerUnavailable:"The backend did not return fertilizer predictions.", topRecommendation:"Top recommendation", alternativeCrop:"Alternative crop", observations:"Price observations", marketTrend:"Market Price Trend", marketTrendLead:"Monthly average market prices returned by the backend.", marketTrendUnavailable:"Market trend is unavailable", marketTrendUnavailableLead:"The backend did not return enough market-price points for a chart.", marketPriceAxis:"Market price (₹)", expectedRevenue:"Expected revenue", sowingWindow:"Sowing window", harvestWindow:"Expected harvest", soilCompatibility:"Soil compatibility", resolvedLocation:"Resolved location", recommendedCount:"recommended crops", buildingPlan:"Building seasonal plan...", harvestAfterSowing:"Harvesting date must be after the sowing date.", urea:"Urea", dap:"DAP", mop:"MOP", zincSulphate:"Zinc Sulphate",
    toolsHint:"Choose a tool to get started.", cropText:"Find crops that fit your place, soil and sowing date.",
    diseaseText:"Upload a leaf photo to check what may be affecting your crop.", plannerText:"Find crops that fit the days your land is available.",
    pestAdvisor:"Pest & Pesticide Advisor", pestAdvisorText:"Select your crop and location to see common pests and pesticide options.",
    findCrops:"Find my crops", checkCrop:"Check a crop", planSeason:"Plan my season", farmerTip:"Keep your location, pincode and sowing date ready for more accurate suggestions.",
    farmAnalysis:"FARM ANALYSIS", newAnalysis:"← New Analysis", dashboardTitle:"Your Farm Dashboard", dashboardLead:"Here is the information received from your farm analysis.",
    back:"← Back", tellFarm:"Tell us about your farm", tellFarmLead:"Enter your farm details and we'll analyze the available data for your location.",
    unable:"Unable to generate recommendation", invalidInput:"Invalid farmer input. Please check the information you entered.", locationNotFound:"Location not found. Please check your location and pincode.", serverError:"The server could not generate the recommendation. Please try again.", backendError:"Unable to connect to the backend. Please make sure the Spring Boot server is running.",
    farmLocation:"Farm Location", farmLocationLead:"Where is your farm located?", location:"Location / Address", locationPlaceholder:"Enter your village, city or area", area:"Farm Area (acres)", areaPlaceholder:"e.g. 2.5", pincode:"Pincode", pincodePlaceholder:"Enter 6-digit pincode", cropDetails:"Crop Details", cropDetailsLead:"Tell us about your upcoming crop", sowingDate:"Sowing Date", getRecommendation:"Get Crop Recommendation", analyzedBy:"Your information is analyzed by the KisanFinTech backend.",
    requiredLocation:"Location is required", requiredPincode:"Pincode is required", validPincode:"Enter a valid 6-digit Indian pincode", requiredArea:"Enter your farm area", requiredSowing:"Sowing date is required",
    cropRecommendations:"Crop Recommendations", threeSuggested:"Three crops suggested from the farm analysis", recommendedCrop:"Recommended Crop", expectedPrice:"Expected Price", confidence:"Confidence", sustainability:"Sustainability", minimumPrice:"Minimum Price", maximumPrice:"Maximum Price", risk:"Risk", estimatedProfit:"Estimated Profit", noRecommendation:"Recommendation data will appear here", noRecommendationText:"Connect the recommendation response from Spring Boot to display the three suggested crops and their market indicators.",
    checkDisease:"📷 Check crop disease", planNext:"📅 Plan the next crop",
    yourSowingWindow:"YOUR SOWING WINDOW", cropsFitTime:"Crops that fit your time", changeDates:"← Change dates", daysAvailable:"days available in", cropOptions:"Your crop options are based on the time your land is free.", suitableCrop:"Suitable crop", investment:"Investment", expectedProfit:"Expected profit", noCrops:"No crops fit this window yet. Try a longer land-available period.", detailedAdvice:"Get detailed crop advice →", checkCropDisease:"Check crop disease →", cropPlannerKicker:"CROP PLANNER", growNext:"What can you grow next?", growLead:"Tell us when your land will be free. We will show crops that fit your available farming time.", villagePlaceholder:"Village, city or area", findSuitable:"Find suitable crops →", completeDetails:"Please complete all five details.",
    cropHealthReport:"CROP HEALTH REPORT", cropCheckReady:"Your crop check is ready", guidanceResult:"This is a guidance result. For severe or spreading symptoms, consult a local agriculture officer.", photoChecked:"Photo checked", whatLook:"What to look for", treatmentGuidance:"TREATMENT GUIDANCE", whatNow:"What you can do now", suggestedPesticide:"Suggested pesticide:", pesticideNote:"Use only as directed on the product label. Wear protective equipment and follow local advice.", checkAnother:"← Check another photo", healthyCrop:"Is your crop healthy?", healthyLead:"Upload a clear photo of the affected leaf or plant. We will identify likely symptoms and next steps.", uploadPhoto:"Upload a crop photo", photoTip:"Take the photo in daylight and keep the affected part in focus.", choosePhoto:"Choose photo", checking:"Checking your crop...", diseaseCheck:"Check for disease →", mockNote:"We use a mock detection service for now. Connect your image model in farmApi.js when it is ready.",
    farmOverview:"Farm Overview", submittedFarm:"Your submitted farm information", coordinates:"Coordinates", notAvailable:"Not available", weatherSoil:"Weather & Soil Conditions", currentEnvironment:"Current environmental information for your farm", temperature:"Temperature", humidity:"Humidity", rainfall:"Rainfall", soilMoisture:"Soil Moisture", soilType:"Soil Type", profitAnalysis:"PROFIT ANALYSIS", profitVsTime:"Crop Profit vs Time", cumulativeProfit:"Estimated cumulative profit through the crop cycle.", estimatedProfitAxis:"Estimated profit (₹)", profit:"Profit", harvestingDate:"Harvesting Date", harvestingDateHi:"कटाई की तारीख", languageEnglish:"English", languageHindi:"हिंदी", pestKicker:"CROP PROTECTION", pestTitle:"Pest & Pesticide", advisorTitle:"Advisor", pestHeroText:"Get a quick crop-protection recommendation based on your crop and farm location.", pestGetAdvice:"Get Pest & Pesticide Advice", pestEnterDetails:"Enter crop details and location to get a focused recommendation.", cropType:"Crop Type", selectCrop:"Select crop", location:"Location", locationPlaceholder:"Village, city or area", pincode:"Pincode", pincodePlaceholder:"6-digit pincode", pestPincodeHint:"Enter a valid 6-digit Indian pincode.", getAdvice:"Get Advice", pestRecommendation:"Pest & Pesticide Recommendation", pestEmptyText:"Select a crop, enter your location and pincode, then click Get Advice.", commonPest:"Common Pest", recommendedPesticide:"Recommended Pesticide", modelAccuracy:"Model Accuracy", riskLevel:"Risk Level", pestRequiredCropLocation:"Please select a crop and enter your location.", smartFarming:"Smart Farming Decisions", loadingTitle:"Analyzing your farm", loadingLead:"Checking the information you provided and preparing your crop guidance.", loadingFarm:"Reading farm details", loadingWeather:"Checking local conditions", loadingCrops:"Preparing crop suggestions",
  },
  hi: {
    home:"होम", crops:"फसल सलाह", disease:"रोग जाँच", planner:"फसल योजना", switchToHindi:"EN",
    cropRecommendation:"फसल सुझाव", diseaseDetector:"रोग पहचान", cropPlanner:"फसल योजनाकार", farmTools:"किसान उपकरण", helpToday:"आज हम कैसे मदद करें?",
    hero:"हर मौसम के लिए बेहतर फैसले।", heroText:"आपके खेत के लिए आसान फसल सलाह, रोग जाँच और फसल योजना।", heroLabel:"स्मार्ट खेती, आसान तरीके से", heroBadge:"🌾 किसानफिनटेक", heroPhotoTag:"हर किसान के लिए बनाया गया", heroReferenceTitle:"बेहतर फसल के लिए बेहतर फैसले।", heroReferenceText:"हर किसान के लिए AI आधारित जानकारी, सरल सलाह और व्यक्तिगत मार्गदर्शन।", healthySoil:"स्वस्थ मिट्टी", healthyCrops:"स्वस्थ फसलें", sustainableFuture:"टिकाऊ भविष्य", greenerTomorrow:"हरित और बेहतर कल की ओर साथ मिलकर।", recommendedFertilizers:"अनुशंसित उर्वरक", fertilizerNamesOnly:"इस फसल के लिए सुझाए गए उर्वरकों के नाम।", fertilizerBasedOnModel:"आपके खेत की परिस्थितियों के आधार पर मॉडल का अनुमान।", recommendedFertilizer:"अनुशंसित उर्वरक", fertilizerUnavailable:"बैकएंड ने उर्वरक सुझाव नहीं भेजा।", topRecommendation:"मुख्य सुझाव", alternativeCrop:"वैकल्पिक फसल", observations:"मूल्य अवलोकन", marketTrend:"बाजार मूल्य रुझान", marketTrendLead:"बैकएंड द्वारा लौटाए गए मासिक औसत बाजार मूल्य।", marketTrendUnavailable:"बाजार रुझान उपलब्ध नहीं है", marketTrendUnavailableLead:"बैकएंड ने ग्राफ के लिए पर्याप्त बाजार मूल्य डेटा नहीं भेजा।", marketPriceAxis:"बाजार मूल्य (₹)", expectedRevenue:"अनुमानित राजस्व", sowingWindow:"बुवाई अवधि", harvestWindow:"अनुमानित कटाई", soilCompatibility:"मिट्टी अनुकूलता", resolvedLocation:"सत्यापित स्थान", recommendedCount:"सुझाई गई फसलें", buildingPlan:"मौसमी योजना तैयार हो रही है...", harvestAfterSowing:"कटाई की तारीख बुवाई की तारीख के बाद होनी चाहिए।", urea:"यूरिया", dap:"डीएपी", mop:"एमओपी", zincSulphate:"जिंक सल्फेट", toolsHint:"शुरू करने के लिए एक उपकरण चुनें।",
    cropText:"अपने स्थान, मिट्टी और बुवाई की तारीख के अनुसार फसलें पाएँ।", diseaseText:"फसल को प्रभावित करने वाली समस्या जानने के लिए पत्ते की फोटो डालें।", plannerText:"जितने दिन जमीन खाली है, उसके अनुसार फसलें पाएँ।", pestAdvisor:"कीट और कीटनाशक सलाह", pestAdvisorText:"फसल और स्थान चुनकर सामान्य कीटों और कीटनाशक विकल्प देखें।", findCrops:"मेरी फसलें खोजें", checkCrop:"फसल जाँचें", planSeason:"मौसम की योजना बनाएँ", farmerTip:"सटीक सुझावों के लिए अपना स्थान, पिनकोड और बुवाई की तारीख तैयार रखें।",
    farmAnalysis:"खेत का विश्लेषण", newAnalysis:"← नया विश्लेषण", dashboardTitle:"आपका खेत डैशबोर्ड", dashboardLead:"आपके खेत के विश्लेषण से मिली जानकारी यहाँ है।", back:"← वापस", tellFarm:"अपने खेत के बारे में बताएँ", tellFarmLead:"अपने खेत की जानकारी दें और हम आपके स्थान के उपलब्ध डेटा का विश्लेषण करेंगे।",
    unable:"सुझाव तैयार नहीं हो सका", invalidInput:"किसान की जानकारी सही नहीं है। कृपया दर्ज की गई जानकारी जाँचें।", locationNotFound:"स्थान नहीं मिला। कृपया स्थान और पिनकोड जाँचें।", serverError:"सर्वर सुझाव तैयार नहीं कर सका। कृपया फिर प्रयास करें।", backendError:"बैकएंड से कनेक्ट नहीं हो सका। कृपया Spring Boot सर्वर चल रहा है या नहीं जाँचें।",
    farmLocation:"खेत का स्थान", farmLocationLead:"आपका खेत कहाँ स्थित है?", location:"स्थान / पता", locationPlaceholder:"गाँव, शहर या क्षेत्र दर्ज करें", area:"खेत का क्षेत्रफल (एकड़)", areaPlaceholder:"जैसे 2.5", pincode:"पिनकोड", pincodePlaceholder:"6 अंकों का पिनकोड दर्ज करें", cropDetails:"फसल की जानकारी", cropDetailsLead:"अपनी आने वाली फसल के बारे में बताएँ", sowingDate:"बुवाई की तारीख", getRecommendation:"फसल सुझाव पाएँ", analyzedBy:"आपकी जानकारी KisanFinTech बैकएंड द्वारा विश्लेषित की जाती है।",
    requiredLocation:"स्थान आवश्यक है", requiredPincode:"पिनकोड आवश्यक है", validPincode:"सही 6 अंकों का भारतीय पिनकोड दर्ज करें", requiredArea:"खेत का क्षेत्रफल दर्ज करें", requiredSowing:"बुवाई की तारीख आवश्यक है",
    cropRecommendations:"फसल सुझाव", threeSuggested:"खेत के विश्लेषण से सुझाई गई तीन फसलें", recommendedCrop:"सुझाई गई फसल", expectedPrice:"अनुमानित कीमत", confidence:"विश्वास स्तर", sustainability:"स्थिरता", minimumPrice:"न्यूनतम कीमत", maximumPrice:"अधिकतम कीमत", risk:"जोखिम", estimatedProfit:"अनुमानित लाभ", noRecommendation:"फसल सुझाव यहाँ दिखाई देंगे", noRecommendationText:"Spring Boot से सुझाव प्रतिक्रिया जोड़ें ताकि तीन सुझाई गई फसलें और उनके बाजार संकेतक दिखाई दें।",
    checkDisease:"📷 फसल रोग जाँचें", planNext:"📅 अगली फसल की योजना बनाएँ",
    yourSowingWindow:"आपकी बुवाई की अवधि", cropsFitTime:"आपके समय के अनुसार फसलें", changeDates:"← तारीख बदलें", daysAvailable:"दिन उपलब्ध हैं", cropOptions:"आपकी जमीन के खाली रहने के समय के आधार पर फसल विकल्प दिए गए हैं।", suitableCrop:"उपयुक्त फसल", investment:"निवेश", expectedProfit:"अनुमानित लाभ", noCrops:"इस अवधि में कोई फसल फिट नहीं होती। जमीन खाली रहने की अवधि बढ़ाकर देखें।", detailedAdvice:"विस्तृत फसल सलाह →", checkCropDisease:"फसल रोग जाँचें →", cropPlannerKicker:"फसल योजनाकार", growNext:"अगली फसल क्या उगाएँ?", growLead:"बताएँ कि आपकी जमीन कब खाली होगी। हम उपलब्ध खेती के समय के अनुसार फसलें दिखाएँगे।", villagePlaceholder:"गाँव, शहर या क्षेत्र", findSuitable:"उपयुक्त फसलें खोजें →", completeDetails:"कृपया सभी पाँच जानकारी पूरी करें।",
    cropHealthReport:"फसल स्वास्थ्य रिपोर्ट", cropCheckReady:"आपकी फसल जाँच तैयार है", guidanceResult:"यह मार्गदर्शन आधारित परिणाम है। लक्षण गंभीर या फैल रहे हों तो स्थानीय कृषि अधिकारी से सलाह लें।", photoChecked:"फोटो जाँची गई", whatLook:"क्या देखें", treatmentGuidance:"उपचार मार्गदर्शन", whatNow:"अभी क्या कर सकते हैं", suggestedPesticide:"सुझाया गया कीटनाशक:", pesticideNote:"उत्पाद के लेबल पर दिए निर्देशों के अनुसार ही उपयोग करें। सुरक्षा उपकरण पहनें और स्थानीय सलाह का पालन करें।", checkAnother:"← दूसरी फोटो जाँचें", healthyCrop:"क्या आपकी फसल स्वस्थ है?", healthyLead:"प्रभावित पत्ते या पौधे की साफ फोटो अपलोड करें। हम संभावित लक्षण और अगले कदम बताएँगे।", uploadPhoto:"फसल की फोटो अपलोड करें", photoTip:"फोटो दिन के उजाले में लें और प्रभावित हिस्से को फोकस में रखें।", choosePhoto:"फोटो चुनें", checking:"फसल जाँची जा रही है...", diseaseCheck:"रोग जाँचें →", mockNote:"अभी हम डेमो डिटेक्शन सेवा का उपयोग कर रहे हैं। तैयार होने पर farmApi.js में अपना इमेज मॉडल जोड़ें।",
    farmOverview:"खेत का विवरण", submittedFarm:"आपके द्वारा दी गई खेत की जानकारी", coordinates:"निर्देशांक", notAvailable:"उपलब्ध नहीं", weatherSoil:"मौसम और मिट्टी की स्थिति", currentEnvironment:"आपके खेत की वर्तमान पर्यावरणीय जानकारी", temperature:"तापमान", humidity:"नमी", rainfall:"वर्षा", soilMoisture:"मिट्टी की नमी", soilType:"मिट्टी का प्रकार", profitAnalysis:"लाभ विश्लेषण", profitVsTime:"समय के साथ फसल लाभ", cumulativeProfit:"पूरे फसल चक्र में अनुमानित संचयी लाभ।", estimatedProfitAxis:"अनुमानित लाभ (₹)", profit:"लाभ", harvestingDate:"कटाई की तारीख", harvestingDateHi:"कटाई की तारीख", languageEnglish:"अंग्रेज़ी", languageHindi:"हिंदी", pestKicker:"फसल सुरक्षा", pestTitle:"कीट और कीटनाशक", advisorTitle:"सलाह", pestHeroText:"अपनी फसल और खेत के स्थान के आधार पर त्वरित फसल-सुरक्षा सुझाव पाएँ।", pestGetAdvice:"कीट और कीटनाशक सलाह पाएँ", pestEnterDetails:"सटीक सुझाव के लिए फसल और स्थान की जानकारी दर्ज करें।", cropType:"फसल का प्रकार", selectCrop:"फसल चुनें", location:"स्थान", locationPlaceholder:"गाँव, शहर या क्षेत्र", pincode:"पिनकोड", pincodePlaceholder:"6 अंकों का पिनकोड", pestPincodeHint:"सही 6 अंकों का भारतीय पिनकोड दर्ज करें।", getAdvice:"सलाह पाएँ", pestRecommendation:"कीट और कीटनाशक सुझाव", pestEmptyText:"फसल, स्थान और पिनकोड चुनकर सलाह पाएँ।", commonPest:"सामान्य कीट", recommendedPesticide:"अनुशंसित कीटनाशक", modelAccuracy:"मॉडल सटीकता", riskLevel:"जोखिम स्तर", pestRequiredCropLocation:"कृपया फसल चुनें और स्थान दर्ज करें।", smartFarming:"स्मार्ट खेती के फैसले", loadingTitle:"आपके खेत का विश्लेषण", loadingLead:"आपकी जानकारी जाँचकर फसल संबंधी सलाह तैयार की जा रही है।", loadingFarm:"खेत की जानकारी पढ़ी जा रही है", loadingWeather:"स्थानीय परिस्थितियाँ जाँची जा रही हैं", loadingCrops:"फसल सुझाव तैयार किए जा रहे हैं",
  }
};

const LanguageContext = createContext();
export function LanguageProvider({ children }) {
  const [language, setLanguage] = useState(() => {
    try { return localStorage.getItem("kisan-language") === "hi" ? "hi" : "en"; } catch { return "en"; }
  });
  useEffect(() => {
    try { localStorage.setItem("kisan-language", language); } catch {}
    document.documentElement.lang = language === "hi" ? "hi" : "en";
  }, [language]);
  const t = (key) => copy[language][key] || copy.en[key] || key;
  return <LanguageContext.Provider value={{ language, setLanguage, t }}>{children}</LanguageContext.Provider>;
}
export const useLanguage = () => useContext(LanguageContext);
